#!/bin/sh
[ -S /hvr/docker.sock ] || {
	echo "WARNING: /hvr/docker.sock not found."
	echo "Try starting the container with -v /var/run:/hvr ?"
}
ln -s /hvr/docker.sock /var/run/docker.sock
if pip freeze | grep -q ^gevent
then GEVENT=gevent
else GEVENT=nogevent
fi
exec napixd noauth $GEVENT
